### ISSUE TITLE
Enable persistent oig-context elements

### ISSUE THREAD

**Issue by shock01** [shock01/oig#22]
When adding oig-context element add ability to persist the context. Meaning that when the element is added to the dom again it should load the data from sessionStorage....
This means that the element somehow needs to assing a unique id that can be used as key for data storage. State of view model needs to be stored on removal of element from DOM

Let element be an instance of oig-context
Let attribute mode be persist
When element is removed from DOM then store viewModel properties inside sessionStorage
When element is appended to DOM again then preserve the viewModel without triggering Obect.observe

**Comment by shock01** [comment]
Not sure yet.....

Should the element (Custom HTML Element) store the persisted state??? Sounds kinda weird

Might be better than if persisted is true that the 'framework' will take care of window unload,location.search change... dom removal should not really matter then because the active viewModel will be present if location has not reloaded or has changed etc....

http://stackoverflow.com/questions/6188584/viewmodel-and-singleton-pattern

**Comment by shock01** [comment]
Might be better to have like 
oigLocator.resolve('viewModelPersistService')
-> then the service can be changed and also then it can be either stored in sessionService...or actually be stored in whateer.


viewModelPersistService.register('key', viewModelRefererce);
viewModelPersistService.resolve('key')

In a kinda way it's weird that the view takes care of this. However there's no need to make controllers / viewmodels singletons thus there can be multiple instances of the same viewModel within an application flow. Which both can have separate state

**Comment by shock01** [comment]
And....do we want to persist eveything???? or should we kinda be able to specify what is persistable???? That way we can prevent actually to have blooted session storage.

Or....should we just use it with care?? Be smart about which viewModels to persist....don't be an idiot

fun is to have like a sessionStorage implemented it can actually be AOP'ed for eg. encrypting or whatever (wild ideas)

maybe something like.....
function Controller () {
/**!persistable*/this.name = 'null';
}

**Comment by Nagogus** [comment]
Maybe it is good idea to provide some pre-saving and pre-loading methods on viewModel?
In that way pre-save will be called as filter before persisting viewModel and user can choose which properties will be returned/saved from viewModel. And same for pre loading which will be executed before restoring viewModel from storage? But if you have pre-save do you need pre-load because everything can be done before saving..

`<div is="oig-context" data-view-model="someViewModel" persist="filterWhatToSavedependingOnSomeConditions">`

**Comment by Nagogus** [comment]
and saving can be even canceled from pre-save method. 
As I see main use case for persisting viewModel is forms, correct me if I am wrong, but if it is then in many cases it should be canceled depends on values in viewModel

**Comment by shock01** [comment]
Persist can. Also mean like collapse expand state of component. Or like a
selection that you want to preserve.so its not directly tied to forms but
more to viewstate
Op 21 mrt. 2015 21:08 schreef "Ruben Nagoga" <notifications@github.com>:
