### ISSUE TITLE
Extend di with values and constants 

### ISSUE THREAD

**Issue by shock01** [shock01/oig#33]
Bind to should accept string and numbers so that properties can be injected these properties can be mutable and immutable 

Bind(x).to(value).mutable()
Bind(x).to(value).immutable()
Where default should be immutable 

Other options 
Bind(x).toValue(y)
Or toConstant(y)

**Comment by shock01** [comment]
/**
* @param {string|number} value
* @param {boolean} mutable
*/
oigLocator.register('test', new ValueResolvable(value, mutable) {
	
	var obj = {};
	Object.defineProperty(obj, {
		value: {
			value: value,
			writable: mutable
		}
	})
	
	return function () {
		return obj.value;
	}
	
});

**Comment by shock01** [comment]
You might need to create a single resolver function that has an innermap with values on that use defineproperty then you can set properties to writable True false and return value from map

Try adding unit test for setting as value and as constant and resolve them after redefining 

As always tdd

**Comment by shock01** [comment]
Also we should prevent access to redefining on oiglocator.register will discuss that later

**Comment by Nagogus** [comment]
Create `ValueContext` and `ValueResolver`, and modify module.js to use different contexts (DI/Value) depends on input value, as we have discussed yesterday.
But it can't be done at the step of calling `bind` method as we don't know type of value and method `to` is called already in `DIContext`. I see two ways either we need to postpone determination of context till `to` method is called (but what to return after `bind` is called?) or change `bind` method to accept to parameters, `(key, value)` and get rid of `to`.

**Comment by shock01** [comment]
I would go for Bind with 2 parameters
Op 22 apr. 2015 21:29 schreef "Ruben Nagoga" <notifications@github.com>:

**Comment by shock01** [comment]
Also we could return an object function from Bind call that has a method to
Functional styled that might be beter
Will ping you shortly
Op 22 apr. 2015 21:29 schreef "Ruben Nagoga" <notifications@github.com>:

**Comment by shock01** [comment]
function OIGBindable(key) {
	this.key = key;
}
OIGBindable.prototype = {
	to: function (value) {
		if(typeof value === 'string' || typeof value === 'number') {
			return new OigValueBinding();
		} else {
			return new OigDIBinding();
		}
	}
}


oig.bind = function (key) {

	return new OIGBindable(key);
}

**Comment by Nagogus** [comment]
Closed. Branch oig-33
