### ISSUE TITLE
Separate the core components from custom elements

### ISSUE THREAD

**Issue by shock01** [shock01/oig#37]
To be Refined:
Goal is to separate the DI, Object observing and viewmodel construction out of the project.
The core should not be dependant on Custom HtmlElement but just use data attributes to make it compatible with IE.

Core module should not have exports , amd or commonjs or whatsoever...that can always be added later on :-)

NB. All the custom elements like ng-if etc are not really what should be part of this small framework.
The view impl should be whatever you want it to be . eg manual dom/ template driven / two way databinding...etc)

- Needs polyfill for object.observe and array.observe (https://github.com/MaxArt2501/object-observe)
- Should be possible to construct views which can update the view when data model changes (eg. re-render a template)
- Use mutation observer to detect new view models
- Should bootstrap on DOMContentLoaded
- could also be change to use data-view="asdasd" where view-model is injected into a new view. when viewModel changes it should dispatch a change event which can be handled by the view to rerender the template
- weakMap can be used to attach viewModels to elements
- add on<event> behaviour to delegate to viewModel
eg. onclick="oig(event,'doSomething(name, 1)')"
of onclick="oig.delegate(event,'doSomething(name, 1)')"
signature:
oig.delegate(event: Event, execute:string, viewModel?: string) 
where viewModel is optional but will delegate by default to current viewmodel
- Use TreeWalker on DOMContentLoaded and on MutationObserver to find view-model nodes
- http://programmers.stackexchange.com/questions/225400/pros-and-cons-of-facebooks-react-vs-web-components-polymer (Actually...when do we need two way binding??? yes when we have a form...so why not just have a view (code-behind) that calls the viewModel with the mutated values?
this will make sure that only the viewmodel will update data (data flows one way)

http://msdn.microsoft.com/en-us/magazine/dd419663.aspx
In a well-designed MVVM architecture, the codebehind for most Views should be empty, or, at most, only contain code that manipulates the controls and resources contained within that view.(1)Sometimes it is also necessary to write code in a View's codebehind that interacts with a ViewModel object, such as hooking an event or calling a method that would otherwise be very difficult to invoke from the ViewModel itself.

**Comment by Nagogus** [comment]
You are back! :)

**Comment by shock01** [comment]
Yeah....new ideas :-) Will call you soon.

**Comment by shock01** [comment]
jQUery like constructor to call viewModel from view??

var oig = function () {
return new oig.fn.init()
}

oig.fn = oig.prototype = {
 constructor: oig,
 init: function () {
 },
 test: function () { console.log('test')
 }
}
oig {}

Can be used like: oig(event).doWhatever();

or oig(element).doWhatever(1, 'propA', 'propB');
or oig(element).view.doWhatever(1, 'propA', 'propB');

oig(event).context.doWhatever(); (shortcut for viewResolver.resolve())'
oig(event).view.doWhatever(this.form) ????
